// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.21.12
// source: kafka_events.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomerCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerCreatedEvent) Reset() {
	*x = CustomerCreatedEvent{}
	mi := &file_kafka_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerCreatedEvent) ProtoMessage() {}

func (x *CustomerCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerCreatedEvent.ProtoReflect.Descriptor instead.
func (*CustomerCreatedEvent) Descriptor() ([]byte, []int) {
	return file_kafka_events_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerCreatedEvent) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CustomerCreatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomerCreatedEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type OrderPlacedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       int64                  `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Items         string                 `protobuf:"bytes,3,opt,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPlacedEvent) Reset() {
	*x = OrderPlacedEvent{}
	mi := &file_kafka_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPlacedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPlacedEvent) ProtoMessage() {}

func (x *OrderPlacedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPlacedEvent.ProtoReflect.Descriptor instead.
func (*OrderPlacedEvent) Descriptor() ([]byte, []int) {
	return file_kafka_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderPlacedEvent) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *OrderPlacedEvent) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *OrderPlacedEvent) GetItems() string {
	if x != nil {
		return x.Items
	}
	return ""
}

type DeliveryStatusUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryID    int64                  `protobuf:"varint,1,opt,name=deliveryID,proto3" json:"deliveryID,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryStatusUpdatedEvent) Reset() {
	*x = DeliveryStatusUpdatedEvent{}
	mi := &file_kafka_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStatusUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStatusUpdatedEvent) ProtoMessage() {}

func (x *DeliveryStatusUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStatusUpdatedEvent.ProtoReflect.Descriptor instead.
func (*DeliveryStatusUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_kafka_events_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryStatusUpdatedEvent) GetDeliveryID() int64 {
	if x != nil {
		return x.DeliveryID
	}
	return 0
}

func (x *DeliveryStatusUpdatedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_kafka_events_proto protoreflect.FileDescriptor

var file_kafka_events_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x58, 0x0a, 0x14,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x5a, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0x54, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x73, 0x61, 0x6e, 0x7a, 0x68, 0x69, 0x65, 0x76,
	0x2f, 0x74, 0x61, 0x63, 0x6f, 0x2d, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_kafka_events_proto_rawDescOnce sync.Once
	file_kafka_events_proto_rawDescData []byte
)

func file_kafka_events_proto_rawDescGZIP() []byte {
	file_kafka_events_proto_rawDescOnce.Do(func() {
		file_kafka_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kafka_events_proto_rawDesc), len(file_kafka_events_proto_rawDesc)))
	})
	return file_kafka_events_proto_rawDescData
}

var file_kafka_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kafka_events_proto_goTypes = []any{
	(*CustomerCreatedEvent)(nil),       // 0: models.CustomerCreatedEvent
	(*OrderPlacedEvent)(nil),           // 1: models.OrderPlacedEvent
	(*DeliveryStatusUpdatedEvent)(nil), // 2: models.DeliveryStatusUpdatedEvent
}
var file_kafka_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kafka_events_proto_init() }
func file_kafka_events_proto_init() {
	if File_kafka_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kafka_events_proto_rawDesc), len(file_kafka_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafka_events_proto_goTypes,
		DependencyIndexes: file_kafka_events_proto_depIdxs,
		MessageInfos:      file_kafka_events_proto_msgTypes,
	}.Build()
	File_kafka_events_proto = out.File
	file_kafka_events_proto_goTypes = nil
	file_kafka_events_proto_depIdxs = nil
}
